### ISSUE TITLE
net48 support 

### ISSUE THREAD

**Issue by smhrazacb** [IcySnex/ReCaptcha.Desktop#1]
please add net48  wpf support

**Comment by IcySnex** [comment]
Hello,

Thank you for your suggestion.
I have updated Recaptcha.Desktop to version 2.1.0. This includes support for .NET Framework 4.8 on WPF and WinForms.

I do not recommend using .NET Framework in 2024 though, since its not really *supported* by Microsoft anymore. I highly suggest porting your application to .NET (Core), but since .NET Framework is still often used in many organizations I have updated this package to multi-target.

Also, please be aware that I have not specifically tested this package on .NET Framework. I have only checked that everything compiles and the basic functionality works correctly. I do not plan on supporting .NET Framework.

Kind Regards.

**Comment by smhrazacb** [comment]
> Hello,
> 
> Thank you for your suggestion. I have updated Recaptcha.Desktop to version 2.1.0. This includes support for .NET Framework 4.8 on WPF and WinForms.
> 
> I do not recommend using .NET Framework in 2024 though, since its not really _supported_ by Microsoft anymore. I highly suggest porting your application to .NET (Core), but since .NET Framework is still often used in many organizations I have updated this package to multi-target.
> 
> Also, please be aware that I have not specifically tested this package on .NET Framework. I have only checked that everything compiles and the basic functionality works correctly. I do not plan on supporting .NET Framework.
> 
> Kind Regards.

جزاك الله خیرًا
